// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetCUBES.Helpers;

#nullable disable

namespace ProjetCUBES.Migrations
{
    [DbContext(typeof(Class.Apply))]
    [Migration("20230109192803_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetCUBES.Model.Article", b =>
                {
                    b.Property<int>("ID_Article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DateFill")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<string>("Grape")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdFamily")
                        .HasColumnType("int");

                    b.Property<int>("IdProvider")
                        .HasColumnType("int");

                    b.Property<string>("Ladder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameArticle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("PriceSup")
                        .HasColumnType("double");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMin")
                        .HasColumnType("int");

                    b.Property<int>("StockProv")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID_Article");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ProjetCUBES.Model.Command", b =>
                {
                    b.Property<int>("Id_Command")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date_Command")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<double>("Price_Command")
                        .HasColumnType("double");

                    b.Property<int>("RefCommand")
                        .HasColumnType("int");

                    b.Property<int>("Status_Comman")
                        .HasColumnType("int");

                    b.HasKey("Id_Command");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("ProjetCUBES.Model.Family", b =>
                {
                    b.Property<int>("ID_Family")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameFamily")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_Family");

                    b.ToTable("Familys");
                });

            modelBuilder.Entity("ProjetCUBES.Model.Job", b =>
                {
                    b.Property<int>("ID_Job")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_Job");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ProjetCUBES.Model.LineCommand", b =>
                {
                    b.Property<int>("Id_LineCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_article")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Ref_Command")
                        .HasColumnType("int");

                    b.HasKey("Id_LineCommande");

                    b.ToTable("LineCommands");
                });

            modelBuilder.Entity("ProjetCUBES.Model.StatusCommand", b =>
                {
                    b.Property<int>("Id_StatusCommand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusCommand");

                    b.ToTable("StatusCommands");
                });

            modelBuilder.Entity("ProjetCUBES.Model.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ProjetCUBES.Model.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstNameUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Idjob")
                        .HasColumnType("int");

                    b.Property<string>("LogInUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassWordUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_User");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
